# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.scim_source_group import SCIMSourceGroup

class TestSCIMSourceGroup(unittest.TestCase):
    """SCIMSourceGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SCIMSourceGroup:
        """Test SCIMSourceGroup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SCIMSourceGroup`
        """
        model = SCIMSourceGroup()
        if include_optional:
            return SCIMSourceGroup(
                id = '',
                group = '',
                group_obj = authentik_client.models.user_group.UserGroup(
                    pk = '', 
                    num_pk = 56, 
                    name = '', 
                    is_superuser = True, 
                    parent = '', 
                    parent_name = '', 
                    attributes = {
                        'key' : null
                        }, ),
                source = '',
                attributes = None
            )
        else:
            return SCIMSourceGroup(
                id = '',
                group = '',
                group_obj = authentik_client.models.user_group.UserGroup(
                    pk = '', 
                    num_pk = 56, 
                    name = '', 
                    is_superuser = True, 
                    parent = '', 
                    parent_name = '', 
                    attributes = {
                        'key' : null
                        }, ),
                source = '',
        )
        """

    def testSCIMSourceGroup(self):
        """Test SCIMSourceGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
