# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.frame_challenge_response_request import FrameChallengeResponseRequest

class TestFrameChallengeResponseRequest(unittest.TestCase):
    """FrameChallengeResponseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FrameChallengeResponseRequest:
        """Test FrameChallengeResponseRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FrameChallengeResponseRequest`
        """
        model = FrameChallengeResponseRequest()
        if include_optional:
            return FrameChallengeResponseRequest(
                component = 'xak-flow-frame'
            )
        else:
            return FrameChallengeResponseRequest(
        )
        """

    def testFrameChallengeResponseRequest(self):
        """Test FrameChallengeResponseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
