# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.country_code_enum import CountryCodeEnum

class TestCountryCodeEnum(unittest.TestCase):
    """CountryCodeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryCodeEnum(self):
        """Test CountryCodeEnum"""
        # inst = CountryCodeEnum()

if __name__ == '__main__':
    unittest.main()
