# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.intent_enum import IntentEnum

class TestIntentEnum(unittest.TestCase):
    """IntentEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntentEnum(self):
        """Test IntentEnum"""
        # inst = IntentEnum()

if __name__ == '__main__':
    unittest.main()
