# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.group_matching_mode_enum import GroupMatchingModeEnum

class TestGroupMatchingModeEnum(unittest.TestCase):
    """GroupMatchingModeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupMatchingModeEnum(self):
        """Test GroupMatchingModeEnum"""
        # inst = GroupMatchingModeEnum()

if __name__ == '__main__':
    unittest.main()
