# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.log_level_enum import LogLevelEnum

class TestLogLevelEnum(unittest.TestCase):
    """LogLevelEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogLevelEnum(self):
        """Test LogLevelEnum"""
        # inst = LogLevelEnum()

if __name__ == '__main__':
    unittest.main()
