# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.10.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.microsoft_entra_provider_group import MicrosoftEntraProviderGroup

class TestMicrosoftEntraProviderGroup(unittest.TestCase):
    """MicrosoftEntraProviderGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MicrosoftEntraProviderGroup:
        """Test MicrosoftEntraProviderGroup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MicrosoftEntraProviderGroup`
        """
        model = MicrosoftEntraProviderGroup()
        if include_optional:
            return MicrosoftEntraProviderGroup(
                id = '',
                microsoft_id = '',
                group = '',
                group_obj = authentik_client.models.user_group.UserGroup(
                    pk = '', 
                    num_pk = 56, 
                    name = '', 
                    is_superuser = True, 
                    parent = '', 
                    parent_name = '', 
                    attributes = {
                        'key' : null
                        }, ),
                provider = 56,
                attributes = None
            )
        else:
            return MicrosoftEntraProviderGroup(
                id = '',
                microsoft_id = '',
                group = '',
                group_obj = authentik_client.models.user_group.UserGroup(
                    pk = '', 
                    num_pk = 56, 
                    name = '', 
                    is_superuser = True, 
                    parent = '', 
                    parent_name = '', 
                    attributes = {
                        'key' : null
                        }, ),
                provider = 56,
                attributes = None,
        )
        """

    def testMicrosoftEntraProviderGroup(self):
        """Test MicrosoftEntraProviderGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
